In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
from sklearn import metrics

In [2]:
data = "SaYoPillow.csv"
dataset = pd.read_csv(data)

In [3]:
dataset.head()

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [4]:
dataset = dataset.rename(columns={'sr.1' : 'sh'})
dataset.head()

sr      rr       t      lm      bo    rem     sh     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630 entries, 0 to 629
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sr      630 non-null    float64
 1   rr      630 non-null    float64
 2   t       630 non-null    float64
 3   lm      630 non-null    float64
 4   bo      630 non-null    float64
 5   rem     630 non-null    float64
 6   sh      630 non-null    float64
 7   hr      630 non-null    float64
 8   sl      630 non-null    int64  
dtypes: float64(8), int64(1)
memory usage: 44.4 KB


In [6]:
dataset['sl'].unique()

array([3, 1, 0, 2, 4])

In [7]:
dataset.sl.value_counts()

3    126
1    126
0    126
2    126
4    126
Name: sl, dtype: int64

In [8]:
qualityType = { 0 : 0, 1 : 0, 2 : 1, 3 : 2, 4 : 2 }
dataset["sl"] =  dataset["sl"].map(qualityType)
dataset.sl.value_counts()

2    252
0    252
1    126
Name: sl, dtype: int64

<h3>Note :</h3>
<p>
Transfrom stress Level to 3 types: 
<ul> 
<li> Not Stressed : 0 </li>
<li> Stressed : 1 </li>
<li> Very Stressed : 2 </li>
</ul>
</p>

In [9]:
fig = px.box(dataset)

fig.show()

<p>
Karena tidak terdapat data outlier, maka dapat langsung dibagi antara data train dan data test nya.
</p>

In [10]:
X = dataset.drop('sl',axis=1).values
y = dataset['sl'].values

In [11]:
X

array([[ 93.8  ,  25.68 ,  91.84 , ...,  99.6  ,   1.84 ,  74.2  ],
       [ 91.64 ,  25.104,  91.552, ...,  98.88 ,   1.552,  72.76 ],
       [ 60.   ,  20.   ,  96.   , ...,  85.   ,   7.   ,  60.   ],
       ...,
       [ 97.504,  27.504,  86.88 , ..., 101.88 ,   0.   ,  78.76 ],
       [ 58.64 ,  19.728,  95.728, ...,  84.32 ,   6.728,  59.32 ],
       [ 73.92 ,  21.392,  93.392, ...,  91.96 ,   4.088,  63.48 ]])

In [12]:
y

array([2, 2, 0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 0, 2, 2, 1, 1, 1,
       1, 2, 2, 0, 1, 0, 2, 1, 0, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 1, 1, 0,
       1, 2, 1, 2, 0, 2, 0, 0, 2, 0, 0, 1, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0,
       0, 1, 2, 0, 0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 1, 0, 0, 0,
       2, 2, 1, 2, 1, 2, 0, 1, 2, 1, 1, 2, 2, 2, 0, 2, 0, 1, 1, 1, 2, 0,
       1, 2, 0, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0,
       2, 2, 0, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 2,
       0, 1, 2, 1, 2, 2, 2, 1, 0, 1, 2, 1, 0, 0, 2, 2, 0, 1, 1, 0, 0, 0,
       0, 2, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0,
       1, 2, 0, 0, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1, 1,
       0, 2, 0, 0, 2, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 1, 2, 2, 0, 2, 1, 2, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0,
       0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 2, 2, 0, 2, 0, 0,
       2, 2, 2, 1, 2, 0, 2, 0, 2, 0, 1, 0, 1, 0, 2,

In [13]:
from sklearn.model_selection import train_test_split
X_trainset, X_testset, y_trainset, y_testset = train_test_split(X, y, test_size=0.25, random_state=4)

<h1> DECISION TREE </h1>

In [14]:
from sklearn.tree import DecisionTreeClassifier

In [15]:
stressTree = DecisionTreeClassifier(criterion="gini", max_depth = 10)
stressTree.fit(X_trainset, y_trainset)

DecisionTreeClassifier(max_depth=10)

In [16]:
predTree = stressTree.predict(X_testset)

In [17]:
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(y_testset, predTree)*100, '%')

DecisionTrees's Accuracy:  99.36708860759494 %


In [18]:
# Export Decision Tree Model
filename = 'dtree_pickle'
pickle.dump(stressTree, open(filename, 'wb'))

<h3>
# DECISION TREE EVALUATION
</h3>

In [19]:
## R2
from sklearn.metrics import r2_score
r2 = r2_score(y_testset, predTree) * 100
print("R-Square : ", r2, '%')

R-Square :  99.2634719373485 %


In [20]:
## MSE
from sklearn.metrics import mean_squared_error
print("MSE : ",mean_squared_error(y_testset, predTree))

MSE :  0.006329113924050633


<h1> SVM </h1>

In [21]:
from sklearn import svm

In [22]:
clf = svm.SVC(kernel='linear', gamma='auto').fit(X_trainset,y_trainset) 

In [23]:
y_predict_scm = clf.predict(X_testset)

In [24]:
print("SVM's Accuracy: ", round(metrics.accuracy_score(y_testset, y_predict_scm)*100,2),"%")

SVM's Accuracy:  100.0 %


In [25]:
# Export SVM Model
filename = 'svm_pickle'
pickle.dump(clf, open(filename, 'wb'))

<h3>
# SVM EVALUATION
</h3>

In [26]:
## R2
from sklearn.metrics import r2_score
r2 = r2_score(y_testset, y_predict_scm) * 100
print("R-Square : ", r2, "%")

R-Square :  100.0 %


In [27]:
## MSE
from sklearn.metrics import mean_squared_error
print("MSE : ",mean_squared_error(y_testset, y_predict_scm))

MSE :  0.0
